In [10]:
import numpy as np
from sklearn import datasets

#Load iris datasets
iris=datasets.load_iris()
X=iris.data[:,:]
y=(iris.target!=0)*1
print("X:",X[:10,:])
print("y",y[:10])

X: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]] 150
y [0 0 0 0 0 0 0 0 0 0]


In [11]:
a=np.arange(150)
np.random.seed(42)
np.random.shuffle(a)
test=list(a[0:30])
train=list(a[30:150])

X_train=X[train]
X_test=X[test]

y_train=y[train]
y_test=y[test]

In [24]:
#general function
def sigmoid(z):
    return 1/(1+np.exp(-z))

def zed(W,b,x):
    return x.dot(W)+b

def prob_prediction(W,b,x):
    return sigmoid(zed(W,b,x))

def cost_func(h,y):
    return (-y*np.log(h)-(1-y)*np.log(1-h)).mean()

#label prediction
def predict(W,b,x):
    prob=prob_prediction(W,b,x)
    return prob>=0.5

#Acc
def evaluate(h_test,y):
    return (h_test==y).mean()*100

In [25]:
##Initialization
W=np.random.uniform(low=-0.1,high=0.1,size=X_train.shape[1])
b=0.0
learning_rate=0.1
epochs=20000

#training:fit the model to the training set
print("TRaining:")
for i in range(epochs):
    #calc predictions
    y_predict=prob_prediction(W,b,X_train)
    
    #calc error
    cost=cost_func(y_predict,y_train)
    
    #calc-gradients
    W_gradient=(1.0/len(X_train))*(y_predict-y_train).dot(X_train)
    b_gradient=(1.0/len(X_train))*np.sum(y_predict-y_train)
    
    #diagnostic output
    if i % 1000==0 : print("Epoch %d: Cost=%f"%(i,cost))
        
    #update parameters
    W=W-(learning_rate*W_gradient)
    b=b-(learning_rate*b_gradient)
    
#Evaluate
print("Testing:")
test_set_predictions=predict(W,b,X_test)
print("Accuracy percentage:",evaluate(test_set_predictions,y_test))

TRaining:
Epoch 0: Cost=0.599393
Epoch 1000: Cost=0.007387
Epoch 2000: Cost=0.003980
Epoch 3000: Cost=0.002774
Epoch 4000: Cost=0.002148
Epoch 5000: Cost=0.001761
Epoch 6000: Cost=0.001498
Epoch 7000: Cost=0.001306
Epoch 8000: Cost=0.001160
Epoch 9000: Cost=0.001044
Epoch 10000: Cost=0.000951
Epoch 11000: Cost=0.000874
Epoch 12000: Cost=0.000809
Epoch 13000: Cost=0.000753
Epoch 14000: Cost=0.000705
Epoch 15000: Cost=0.000663
Epoch 16000: Cost=0.000626
Epoch 17000: Cost=0.000593
Epoch 18000: Cost=0.000563
Epoch 19000: Cost=0.000537
Testing:
Accuracy percentage: 100.0
